seminario.web/Controllers/CasosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using seminario.web.Models;
using seminario.web.Negocio;
using seminario.web.Utilidades;

namespace seminario.web.Controllers
{
    [TypeFilter(typeof(ValidarSesionFilter))]
    public class CasosController : BaseController
    {
        private readonly NCasos _casos;
        private readonly NCatalogos _catalogos;
        private readonly NClientes _clientes;
        private readonly NUsuarios _usuarios;
        private readonly NVisitas _visitas;
        private readonly IOptions<AppSettings> _options;

        public CasosController(NCasos casos, NCatalogos catalogos,
            NClientes clientes, NUsuarios usuarios, NVisitas visitas,
            IHttpContextAccessor context, IOptions<AppSettings> options)
            : base(context, options)
        {
            _casos = casos;
            _catalogos = catalogos;
            _clientes = clientes;
            _usuarios = usuarios;
            _visitas = visitas;
            _options = options;
        }

        #region Administración de Casos
        public async Task<IActionResult> Index()
        {
            try
            {
                List<Categoria> categorias = await _catalogos.ObtenerCatalogos<Categoria>(EnumCatalogos.Categoria);

                ViewBag.Categorias = categorias ?? new List<Categoria>();
            }
            catch
            {
            }

            return View();
        }

        [HttpGet]
        public async Task<JsonResult> ListaCasos()
        {
            try
            {
                List<Caso> casos = await _casos.ObtenerCasos();

                List<string> itemString = new List<string>();
                string baseButton = "<button type=\"button\" class=\"btn btn-outline-@btn\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"@tooltip\" onclick=\"@functionJS\"><i class=\"fa @fai\" aria-hidden=\"true\"></i></button>";

                foreach (var item in casos)
                {
                    itemString.Add(item.ID.ToString());
                    itemString.Add($"{item.Cliente.Nombre} {item.Cliente.Apellido}");
                    itemString.Add(item.CodigoSeguimiento);
                    itemString.Add(item.Observacion);
                    itemString.Add(item.Categoria.Nombre);
                    itemString.Add(item.Visitas?.Count().ToString());
                    itemString.Add(item.Cerrado ? "Cerrado" : "Abierto");

                    string botones = "<div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">";
                    if (!item.Cerrado)
                    {
                        botones += baseButton.Replace("@btn", "warning")
                            .Replace("@tooltip", "Editar")
                            .Replace("@fai", "fa-pencil-square-o")
                            .Replace("@functionJS", $"ObtenerCaso({item.ID})");
                        botones += baseButton.Replace("@btn", "primary")
                            .Replace("@tooltip", "Generar Visita")
                            .Replace("@fai", "fa-plane")
                            .Replace("@functionJS", $"ProgramarVisita({item.ID})");
                        botones += baseButton.Replace("@btn", "secondary")
                            .Replace("@tooltip", "Ver Lista de Visita")
                            .Replace("@fai", "fa-globe")
                            .Replace("@functionJS", $"ListarVisitas({item.ID})");
                        botones += baseButton.Replace("@btn", "info")
                            .Replace("@tooltip", "Cerrar")
                            .Replace("@fai", "fa-times")
                            .Replace("@functionJS", $"CerrarCaso({item.ID})");
                        botones += baseButton.Replace("@btn", "danger")
                            .Replace("@tooltip", "Eliminar")
                            .Replace("@fai", "fa-trash-o")
                            .Replace("@functionJS", $"EliminarCaso({item.ID})");
                    }
                    botones += "</div>";

                    itemString.Add(botones);
                }

                return Json(itemString);
            }
            catch (Exception ex)
            {
                Result response = new()
                {
                    Resultado = false,
                    Mensaje = ex.Message
                };
                return Json(response);
            }
        }

        [HttpPost]
        public async Task<JsonResult> CrearEditarCasos(Caso caso)
        {
            try
            {
                Result resultado;
                if (caso.ID > 0)
                    resultado = await _casos.EditarCaso(caso);
                else
                    resultado = await _casos.AgregarCaso(caso);

                return Json(resultado);
            }
            catch (Exception ex)
            {
                return Json(new Result() { Resultado = false, Mensaje = ex.Message });
            }
        }

        [HttpGet]
        public async Task<JsonResult> CerrarCaso(string id)
        {
            try
            {
                Result resultado = await _casos.CerrarCaso(id);

                return Json(resultado);
            }
            catch (Exception ex)
            {
                return Json(new Result() { Resultado = false, Mensaje = ex.Message });
            }
        }

        [HttpGet]
        public async Task<JsonResult> ObtenerCaso(int id)
        {
            try
            {
                Caso casos = await _casos.ObtenerCaso(id);

                return Json(casos);
            }
            catch (Exception ex)
            {
                return Json(new Result() { Resultado = false, Mensaje = ex.Message });
            }
        }

        [HttpGet]
        public async Task<JsonResult> EliminarCaso(string id)
        {
            try
            {
                Result resultado = await _casos.EliminarCaso(id);

                return Json(resultado);
            }
            catch (Exception ex)
            {
                return Json(new Result() { Resultado = false, Mensaje = ex.Message });
            }
        }
        #endregion

        #region Registro de Casos
        public async Task<IActionResult> Registro()
        {
            try
            {
                List<Categoria> categorias = await _catalogos.ObtenerCatalogos<Categoria>(EnumCatalogos.Categoria);

                ViewBag.Categorias = categorias ?? new List<Categoria>();
            }
            catch
            {
            }

            return View();
        }

        [HttpGet]
        public async Task<JsonResult> ListaClientes()
        {
            try
            {
                List<Cliente> clientes = await _clientes.ObtenerClientes();

                List<string> itemString = new List<string>();
                string baseButton = "<button type=\"button\" class=\"btn btn-outline-@btn\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"@tooltip\" onclick=\"@functionJS\"><i class=\"fa @fai\" aria-hidden=\"true\"></i></button>";

                if (clientes != null && clientes.Count > 0)
                    foreach (var item in clientes.Where(c => c.Estado).ToList())
                    {
                        itemString.Add(item.ID.ToString());
                        itemString.Add(item.Documento);
                        itemString.Add(item.Nombre);
                        itemString.Add(item.Apellido);
                        itemString.Add(item.Telefono);
                        itemString.Add(item.Correo);
                        string botones = "<div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">";
                        botones += baseButton.Replace("@btn", "info")
                            .Replace("@tooltip", "Seleccionar")
                            .Replace("@fai", "fa-hand-o-up")
                            .Replace("@functionJS", $"SeleccionarCliente({item.ID}, '{item.Nombre} {item.Apellido}')");
                        botones += "</div>";
                        itemString.Add(botones);
                    }

                return Json(itemString);
            }
            catch (Exception ex)
            {
                Result response = new()
                {
                    Resultado = false,
                    Mensaje = ex.Message
                };
                return Json(response);
            }
        }

        [HttpGet]
        public async Task<JsonResult> ListaTecnicos()
        {
            try
            {
                List<UserCompleto> usuarios = await _usuarios.ObtenerUsuarios();

                List<string> itemString = new List<string>();
                string baseButton = "<button type=\"button\" class=\"btn btn-outline-@btn\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"@tooltip\" onclick=\"@functionJS\"><i class=\"fa @fai\" aria-hidden=\"true\"></i></button>";

                if (usuarios != null && usuarios.Count > 0)
                    foreach (var item in usuarios.Where(c => c.Estado && c.Rol.Nombre.Equals(_options.Value.RolNombre)).ToList())
                    {
                        itemString.Add(item.ID.ToString());
                        itemString.Add(item.Nombre);
                        itemString.Add(item.Correo);
                        itemString.Add($"<img src='data:image/png;base64, {item.FotoPerfil}' class='rounded img-thumbnail' width='80' height='80' alt='Not Found' />");
                        itemString.Add(item.Agencia.Direccion);
                        string botones = "<div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">";
                        botones += baseButton.Replace("@btn", "info")
                            .Replace("@tooltip", "Seleccionar")
                            .Replace("@fai", "fa-hand-o-up")

seminario.web/Views/Casos/Index.cshtml
@{
    ViewData["Title"] = "Administración de Casos";
}

<script type="text/javascript">
    var urlClientes = '@Url.Action("ListaClientes", "Casos")';
    var urlTecnicos = '@Url.Action("ListaTecnicos", "Casos")';
    var urlCasos = '@Url.Action("ListaCasos", "Casos")';
    var encabezadosClientes = ['ID', 'Documento', 'Nombres', 'Apellidos', 'Teléfono', 'Correo', '']
    var encabezadosTecnicos = ['ID', 'Nombres', 'Correo', 'Foto de Perfil', 'Agencia', '']
    var encabezadosCasos = ['ID', 'Cliente', 'Código de Seguimiento', 'Observación', 'Categoría', 'Visitas<br>Programadas', 'Estado', '']
    var clienteID = 0;
    var tecnicoID = 0;
    var casoID = 0;

    $(document).ready(function () {
        LlenarDataTable(urlClientes, 'clientesDiv', encabezadosClientes);
        LlenarDataTable(urlTecnicos, 'tecnicosDiv', encabezadosTecnicos);
        LlenarDataTable(urlCasos, 'casosDiv', encabezadosCasos)
    });

    function AbrirModalCliente() {
        $("#modalListadoClientes").modal('show');
    }

    function AbrirModalUsuario() {
        $("#modalListadoTecnicos").modal('show');
    }

    function RespuestaCrearCasos(data) {
        if (data.resultado) {
            Alerta("Éxito", data.mensaje, "success")
            LlenarDataTable(urlCasos, 'casosDiv', encabezadosCasos)
            ClearControlModal();
        } else {
            Alerta("Alerta", data.mensaje, "warning")
        }
    }

    function CerrarCaso(id) {
        OpenWaitDialog()
        var urlGetStudent = '@Url.Action("CerrarCaso", "Casos")' + '?id=' + id;
        $.ajax({
            url: urlGetStudent,
            type: 'GET',
            success: function (result) {
                if (result.resultado) {
                    Alerta("Éxito", result.mensaje, "success")
                    LlenarDataTable(urlCasos, 'casosDiv', encabezadosCasos)
                } else {
                    Alerta("Alerta", result.mensaje, "warning")
                }
                CloseWaitDialog()
            },
            error: function () {
                console.log("Fallo al eliminar el caso");
                CloseWaitDialog()
            }
        });
    }

    function ObtenerCaso(id) {
        OpenWaitDialog()
        var urlGetCommunity = '@Url.Action("ObtenerCaso", "Casos")' + '?id=' + id;
        $("#TitleCreateUpdate").text('Editar Caso');
        $.ajax({
            url: urlGetCommunity,
            type: 'GET',
            success: function (result) {
                if (result.resultado != null && result.resultado != undefined) {
                    Alerta("Alerta", result.mensaje, "warning");
                } else {
                    casoID = result.id;
                    $("#CasoID").val(result.id);
                    clienteID = result.clienteID;
                    $("#ClienteID").val(result.clienteID);
                    $("#Cliente").val(result.cliente.nombre + ' ' + result.cliente.apellido);
                    $("#Observacion").val(result.observacion);
                    $("#CategoriaID").val(result.categoriaID);
                    $("#crearCasosModal").modal("show");
                }
                CloseWaitDialog()
            },
            error: function () {
                console.log("Fallo al obtener el caso");
                CloseWaitDialog()
            }
        });
    }

    function ProgramarVisita(id) {
        $("#VisitaCasoID").val(id);
        $("#crearVisitaModal").modal("show");
    }

    function ListarVisitas(id) {
        var urlSeguimiento = '@Url.Action("Seguimiento", "Casos")' + '?id=' + id;
        window.location.href = urlSeguimiento;
    }

    function EliminarCaso(id) {
        OpenWaitDialog()
        var urlGetStudent = '@Url.Action("EliminarCaso", "Casos")' + '?id=' + id;
        $.ajax({
            url: urlGetStudent,
            type: 'GET',
            success: function (result) {
                if (result.resultado) {
                    Alerta("Éxito", result.mensaje, "success")
                    LlenarDataTable(urlCasos, 'casosDiv', encabezadosCasos)
                } else {
                    Alerta("Alerta", result.mensaje, "warning")
                }
                CloseWaitDialog()
            },
            error: function () {
                console.log("Fallo al eliminar el caso");
                CloseWaitDialog()
            }
        });
    }

    function ValidarCampos() {
        if (clienteID == 0) {
            Alerta("Alerta", "Debe seleccionar un cliente para crear un caso", "warning")
            return false;
        }

        const observacion = $("#Observacion").val();

        if (observacion == "") {
            Alerta("Alerta", "Debe ingresar las observaciones o detalles del caso", "warning")
            return false;
        }

        return true;
    }

    function ValidarCamposVisita() {
        if (tecnicoID == 0) {
            Alerta("Alerta", "Debe seleccionar un técnico para programar la visita", "warning")
            return false;
        }

        const fechaVisita = $("#FechaVisita").val();

        if (fechaVisita == "") {
            Alerta("Alerta", "Debe ingresar fecha de visita para la visita", "warning")
            return false;
        }

        return true;
    }

    function SeleccionarCliente(id, nombre) {
        $("#ClienteID").val(id);
        clienteID = id;
        $("#Cliente").val(nombre);
        $("#modalListadoClientes").modal('hide');
    }

    function SeleccionarTecnico(id, nombre) {
        $("#UsuarioID").val(id);
        tecnicoID = id;
        $("#Usuario").val(nombre);
        $("#modalListadoTecnicos").modal('hide');
    }

    function ClearControlModal() {
        casoID = 0;
        $("#CasoID").val('0');
        clienteID = 0;
        $("#ClienteID").val('0');
        $("#Cliente").val('');
        $("#Observacion").val('');
        $("#CategoriaID").val(1);

        tecnicoID = 0;
        $("#VisitaCasoID").val('');
        $("#Usuario").val('');
        $("#FechaVisita").val('');

        $("#TitleCreateUpdate").text('Crear Caso');
        $("#crearVisitaModal").modal("hide");
        $("#crearCasosModal").modal("hide");
    }
</script>

<div class="row">
    <div class="col-12 col-md-6">
        <h1>Casos</h1>
    </div>
    <div class="col-12 col-md-6">
        <button type="button" class="float-sm-end btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#crearCasosModal" onclick="ClearControlModal()">Crear Caso</button>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-12 table-responsive" id="casosDiv"></div>
</div>

<div class="modal fade" id="crearCasosModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="TitleCreateUpdate" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-action="CrearEditarCasos" asp-controller="Casos"
                  data-ajax="true" data-ajax-method="POST"
                  data-ajax-begin="OpenWaitDialog()"
                  data-ajax-success="RespuestaCrearCasos(data)">
                <div class="modal-header">
                    <h5 class="modal-title" id="TitleCreateUpdate"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <input type="text" hidden="hidden" id="CasoID" name="caso.ID" readonly="readonly" />
                        <input type="text" hidden="hidden" id="ClienteID" name="caso.ClienteID" readonly="readonly" />
                        <div class="form-floating mt-3 mb-3">
                            <input type="text" class="form-control" value="Haz click para seleccionar un cliente" onclick="AbrirModalCliente()" id="Cliente" name="caso.Cliente" autocomplete="off" readonly="readonly" placeholder="Ingrese al cliente" />
                            <label for="Cliente" class="form-label">Cliente</label>
                        </div>
                        <div class="form-floating mb-3">
                            <textarea type="text" class="form-control" id="Observacion" name="caso.Observacion" autocomplete="off" placeholder="Ingrese una observación"></textarea>
                            <label for="Observacion" class="form-label">Observación</label>
                        </div>
                        <div class="form-floating mb-3">
                            <select class="form-select" id="CategoriaID" name="caso.CategoriaID" aria-label="Floating label select example">
                                @foreach (var item in ViewBag.Categorias)
                                {
                                    <option value="@item.ID">@item.Nombre</option>
                                }
                            </select>
                            <label for="CategoriaID" class="form-label">Categoría</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" onclick="return ValidarCampos()" class="btn btn-outline-success">Guardar</button>
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="crearVisitaModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="TitleCreateUpdateVisita" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-action="CrearVisita" asp-controller="Casos"
                  data-ajax="true" data-ajax-method="POST"
                  data-ajax-begin="OpenWaitDialog()"
                  data-ajax-success="RespuestaCrearCasos(data)">
                <div class="modal-header">
                    <h5 class="modal-title" id="TitleCreateUpdateVisita">Programar Visita</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <input type="text" hidden="hidden" id="VisitaCasoID" name="visita.CasoID" readonly="readonly" />
                        <input type="text" hidden="hidden" id="UsuarioID" name="visita.UsuarioID" readonly="readonly" />
                        <div class="form-floating mt-3 mb-3">
                            <input type="text" class="form-control" value="Haz click para seleccionar un usuario" onclick="AbrirModalUsuario()" id="Usuario" name="caso.Usuario" autocomplete="off" readonly="readonly" placeholder="Ingrese al usuario" />
                            <label for="Usuario" class="form-label">Técnico</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="date" class="form-control" id="FechaVisita" name="visita.FechaVisita" autocomplete="off" placeholder="Ingrese la Fecha de Visita" />
                            <label for="FechaVisita" class="form-label">Fecha de Visita</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" onclick="return ValidarCamposVisita()" class="btn btn-outline-success">Crear Visita</button>
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="modalListadoClientes" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalListadoClientesLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalListadoClientesLabel">Clientes</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="col-12 table-responsive" id="clientesDiv"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalListadoTecnicos" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalListadoTecnicosLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalListadoTecnicosLabel">Técnicos</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="col-12 table-responsive" id="tecnicosDiv"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

seminario.web/Views/Casos/Registro.cshtml
@{
    ViewData["Title"] = "Registro de Casos";
}

<script>
    var urlClientes = '@Url.Action("ListaClientes", "Casos")';
    var encabezadosClientes = ['ID', 'Documento', 'Nombres', 'Apellidos', 'Teléfono', 'Correo', '']
    var clienteID = 0;

    $(document).ready(function () {
        LlenarDataTable(urlClientes, 'clientesDiv', encabezadosClientes);
    });

    function AbrirModalCliente() {
        $("#modalListadoClientes").modal('show');
    }

    function ValidarCampos() {
        if (clienteID == 0) {
            Alerta("Alerta", "Debe seleccionar un cliente para crear un caso", "warning")
            return false;
        }

        const observacion = $("#Observacion").val();

        if (observacion == "") {
            Alerta("Alerta", "Debe ingresar las observaciones o detalles del caso", "warning")
            return false;
        }

        return true;
    }

    function SeleccionarCliente(id, nombre) {
        $("#ClienteID").val(id);
        clienteID = id;
        $("#Cliente").val(nombre);
        $("#modalListadoClientes").modal('hide');
    }

    function LimpiarCampos(){
        $("#ClienteID").val(0);
        clienteID = 0;
        $("#Cliente").val("");
        $("#Observacion").val("");
    }

    function RespuestaCrearCasos(data) {
        if (data.resultado) { 
            Alerta("Éxito", data.mensaje, "success")
            LimpiarCampos();
        }else{
            Alerta("Alerta", data.mensaje, "warning")
        }
    }

</script>

<div class="row">
    <div class="col-12 col-md-6">
        <h1>Registra un nuevo caso</h1>
    </div>
    <div class="col-12 col-md-6">
        @* <button type="button" class="float-sm-end btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#crearAgenciasModal" onclick="ClearControlModal()">Crear Agencia</button> *@
    </div>
</div>

<hr />

<form asp-action="CrearEditarCasos" asp-controller="Casos"
      data-ajax="true" data-ajax-method="POST"
      data-ajax-begin="OpenWaitDialog()"
      data-ajax-success="RespuestaCrearCasos(data)">
    <div class="row justify-content-center">
        <div class="col-6  border border-gray border-2 rounded">
            <input type="text" hidden="hidden" id="ClienteID" name="caso.ClienteID" readonly="readonly" />
            <div class="form-floating mt-3 mb-3">
                <input type="text" class="form-control" value="Haz click para seleccionar un cliente" onclick="AbrirModalCliente()" id="Cliente" name="caso.Cliente" autocomplete="off" readonly="readonly" placeholder="Ingrese al cliente" />
                <label for="Cliente" class="form-label">Cliente</label>
            </div>
            <div class="form-floating mb-3">
                <textarea type="text" class="form-control" id="Observacion" name="caso.Observacion" autocomplete="off" placeholder="Ingrese una observación"></textarea>
                <label for="Observacion" class="form-label">Observación</label>
            </div>
            <div class="form-floating mb-3">
                <select class="form-select" id="CategoriaID" name="caso.CategoriaID" aria-label="Floating label select example">
                    @foreach (var item in ViewBag.Categorias)
                    {
                        <option value="@item.ID">@item.Nombre</option>
                    }
                </select>
                <label for="CategoriaID" class="form-label">Categoría</label>
            </div>
            <div class="justify-content-center mb-3">
                <button type="submit" onclick="return ValidarCampos()" class="btn btn-outline-success">Registrar</button>
            </div>
        </div>
    </div>
</form>

<div class="modal fade" id="modalListadoClientes" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalListadoClientesLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalListadoClientesLabel">Clientes</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="col-12 table-responsive" id="clientesDiv"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>